set (SINK_LIBRARIES "")
if (HAVE_MFX_SINK)
	if(HAVE_WAYLAND_RENDERER)
		pkg_check_modules (WAYLAND_CLIENT REQUIRED wayland-client)
		if (WAYLAND_CLIENT_FOUND)
			include_directories (${WAYLAND_CLIENT_INCLUDE_DIRS})
			LIST (APPEND SINK_LIBRARIES ${WAYLAND_CLIENT_LIBRARIES})
			SET (HAVE_WAYLAND 1)
		endif()
		if(HAVE_EGL_RENDERER)
			pkg_check_modules (EGL REQUIRED egl)
			if(EGL_FOUND)
				include_directories(${EGL_INCLUDE_DIRS})
				LIST(APPEND SINK_LIBRARIES ${EGL_LIBRARIES})
				SET (HAVE_EGL 1)
			endif()
			pkg_check_modules (WAYLAND_EGL REQUIRED wayland-egl)
			if(WAYLAND_EGL_FOUND)
				include_directories(${WAYLAND_EGL_INCLUDE_DIRS})
				LIST(APPEND SINK_LIBRARIES ${WAYLAND_EGL_LIBRARIES})
			endif()
		endif()
	endif()
	if(HAVE_X11_RENDERER)
		pkg_check_modules (X11 REQUIRED x11)
		pkg_check_modules (XKB xkbcommon)
		pkg_check_modules (XRANDR xrandr)
		if (X11_FOUND)
			include_directories (${X11_INCLUDE_DIRS})
			LIST (APPEND SINK_LIBRARIES ${X11_LIBRARIES})
			SET (HAVE_X11 1)
		endif()
		if (XKB_FOUND)
			include_directories (${XKB_INCLUDE_DIRS})
			LIST (APPEND SINK_LIBRARIES ${XKB_LIBRARIES})
			SET (HAVE_XKBLIB 1)
		endif()
		if (XRANDR_FOUND)
			include_directories (${XRANDR_INCLUDE_DIRS})
			LIST (APPEND SINK_LIBRARIES ${XRANDR_LIBRARIES})
			SET (HAVE_XRANDR 1)
		endif()
		if(HAVE_EGL_RENDERER)
			pkg_check_modules (EGL REQUIRED egl)
			if(EGL_FOUND)
				include_directories(${EGL_INCLUDE_DIRS})
				LIST(APPEND SINK_LIBRARIES ${EGL_LIBRARIES})
				SET (HAVE_EGL 1)
			endif()
		endif()
	endif()
endif()
