function(FindVC1 libs)
  set(PARSER_LIB "")
  pkg_check_modules(GSTREAMER_CODECPARSERS gstreamer-codecparsers-1.0)
  pkg_check_modules(GSTREAMER_PBUTILS gstreamer-pbutils-1.0)
  if((NOT GSTREAMER_CODECPARSERS_FOUND) OR (NOT GSTREAMER_PBUTILS_FOUND))
    set(MFX_VC1_PARSER 0 PARENT_SCOPE)
  endif()
  if(GSTREAMER_CODECPARSERS_FOUND)
    list(APPEND PARSER_LIB ${GSTREAMER_CODECPARSERS_LIBRARIES})
    include_directories (${GSTREAMER_CODECPARSERS_INCLUDE_DIRS})
  endif()
  if(GSTREAMER_PBUTILS_FOUND)
    list(APPEND PARSER_LIB ${GSTREAMER_PBUTILS_LIBRARIES})
    include_directories (${GSTREAMER_PBUTILS_INCLUDE_DIRS})
  endif()
  set(${libs} ${${libs}} ${PARSER_LIB} PARENT_SCOPE)
endfunction(FindVC1)
